config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[show edit update destroy]
  before_action :check_permission, only: %i[edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(permitted_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def create
    @post = current_user.posts.new(permitted_params)
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def check_permission
    redirect_to posts_path if @post.user != current_user
  end

  def permitted_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
  def is_post_author?(post)
    post.user == current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <%= link_to root_path, class: 'my-0 mr-md-auto font-weight-normal' do %>
        <h5>Blog</h5>
      <% end %>
      <nav class="my-2 my-md-0 mr-md-3">
        <%= link_to 'Create post', new_post_path, class: 'p-2 text-dark' %>
        <% if user_signed_in? %>
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-primary'%>
        <% else %>
          <%= link_to 'Sign in', user_session_path, class: 'btn btn-primary'%>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-outline-primary'%>
        <% end%>
      </nav>
    </div>
    <div class="container">
      <div class="col">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<% if post.errors.present? %>
  <div>
    <ul>
      <% post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  <div>
  <br>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <br>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render partial: 'form', locals: { post: @post } %>

app/views/posts/index.html.erb
<h1 class="mb-4"> Blog posts </h1>
<div class="row">
  <% @posts.each do |post| %>
      <div class="col-xs-12 col-md-3 mb-3">
        <img src="https://picsum.photos/300/300/?random" class="img-fluid" />
      </div>
      <div class="col-xs-12 col-md-9">
        <%= link_to post_path(post), class: 'bd-title' do %>
          <h2><%= post.title %></h2>
        <% end %>
        <p><%= post.content %></p>
      </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>Create new post</h1>

<%= render partial: 'form', locals: { post: @post } %>

app/views/posts/show.html.erb
<img src="https://picsum.photos/1200/300/?image=966" class="mb-5" />
<h1><%= @post.title %></h1>
<p><%= @post.created_at.to_date %></p>
<p><%= @post.content %></p>

<% if is_post_author?(@post) %>
  <%= link_to 'Edit post', edit_post_path(@post), class: 'btn btn-primary' %>
  <%= link_to 'Destroy post', post_path, method: :delete, class: 'btn btn-outline-primary' %>
<% end %>